#The goal of this yml is to have the parameters of the KMeans model

nb_points_region: 1000

path_save: data/data_generated.npy

final_save_path: "data/final_cluster_position.npy"

final_data_save_path: "data/final_clustered_data.npy"

to_cluster_data_path: "data/data_to_cluster.npy"

final_parameter_path: "configs/final_params.json"

path_config_model: "configs/model_params.yml"

path_config_file: "configs/data_params.yml"

path_config_default: "configs/default_params.yml"